---
  
  # local playbook
  
  - hosts: all
    tasks:
      
      # ++ docker conteinerio sukurimas
      - name: container sendapilocal
        docker_container:
          name: geoip
          image: juozasl/docker:phpapp
          state: started
          restart: yes
          recreate: yes
          restart_policy: false
          pull: true
          volumes:
            - ../api/:/var/www/app/
          ports:
            - '8099:80'
          env:
            FRAMEWORK: 'laravel'

      # ++ composerio instalinimas tiesiai i dockeri
      - shell: docker exec geoip php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - shell: docker exec geoip php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - shell: docker exec geoip php composer-setup.php
      - shell: docker exec geoip php -r "unlink('composer-setup.php');"
      